// Contenido y evaluaciones de los 18 módulos de MichiHub Educación.
// Cada módulo: id, titulo, temas:[{n:nombre, d:descripcion}], preguntas:[{p,o:[opciones],c:indiceCorrecta}]
window.MODULOS = [

{ id:1, titulo:"Computación y herramientas", temas:[
    {n:"Hardware y software", d:"El hardware es todo lo físico de una computadora: el procesador, la memoria, el disco, la pantalla. El software es el conjunto de instrucciones que le dicen a ese hardware qué hacer."},
    {n:"Sistemas operativos", d:"El sistema operativo (Windows, macOS, Linux, Android, iOS) administra el hardware y permite que las demás aplicaciones funcionen."},
    {n:"Archivos, permisos y procesos", d:"Todo lo que guardas es un archivo, organizado en carpetas, con permisos que definen quién puede leerlo, escribirlo o ejecutarlo. Un proceso es un programa en ejecución."},
    {n:"Terminal, Bash y PowerShell", d:"La terminal permite darle instrucciones a la computadora escribiendo comandos. Bash es el lenguaje de comandos más común en Linux/macOS; PowerShell, en Windows."},
    {n:"Linux", d:"Es un sistema operativo gratuito y de código abierto, con muchas distribuciones, y el más usado en servidores de internet."},
    {n:"Redes, IP, DNS, HTTP, HTTPS y TLS", d:"Cada dispositivo tiene una IP; el DNS traduce nombres a esas IP; HTTP es el lenguaje entre navegador y servidor, y HTTPS es lo mismo pero cifrado con TLS."},
    {n:"Instalación de herramientas", d:"Un gestor de paquetes (apt, Homebrew, npm) permite instalar, actualizar y quitar herramientas con un solo comando."},
    {n:"Variables de entorno", d:"Son valores de configuración fuera del código, como claves o rutas, que evitan tener datos sensibles escritos directamente en el programa."},
    {n:"Depuración y solución de problemas", d:"Depurar es encontrar por qué algo no funciona: leer el error con calma, revisar paso a paso y comprobar una hipótesis a la vez."},
], preguntas:[
    {p:"¿Cuál de estos es un ejemplo de hardware?", o:["Sistema operativo","Disco duro","Navegador web","Aplicación de mensajería"], c:1},
    {p:"¿Cuál es la función principal de un sistema operativo?", o:["Diseñar páginas web","Administrar el hardware y ejecutar programas","Conectar dispositivos Bluetooth únicamente","Traducir código a otro idioma"], c:1},
    {p:"¿Qué controla si un usuario puede leer, escribir o ejecutar un archivo?", o:["El nombre del archivo","Los permisos","La extensión","El tamaño"], c:1},
    {p:"¿Qué comando muestra el contenido de una carpeta en Linux/Mac?", o:["cd","ls","rm","mkdir"], c:1},
    {p:"¿Qué es una distribución de Linux?", o:["Un antivirus","Una versión empaquetada del sistema con software adicional","Un navegador","Un lenguaje de programación"], c:1},
    {p:"¿Qué hace el DNS?", o:["Cifra las contraseñas","Traduce nombres de dominio a direcciones IP","Comprime archivos","Enruta correos electrónicos"], c:1},
    {p:"¿Qué es un gestor de paquetes?", o:["Un editor de texto","Una herramienta para instalar y actualizar software fácilmente","Un tipo de base de datos","Un protocolo de red"], c:1},
    {p:"¿Para qué se usan las variables de entorno?", o:["Para diseñar interfaces","Para guardar configuración fuera del código","Para compilar programas","Para conectar a internet"], c:1},
    {p:"¿Qué significa depurar un programa?", o:["Borrar el código","Encontrar y corregir errores","Traducirlo a otro lenguaje","Hacerlo más rápido"], c:1},
]},

{ id:2, titulo:"Programación", temas:[
    {n:"Lógica y algoritmos", d:"Un algoritmo es una secuencia ordenada de instrucciones que resuelve un problema, la base de pensar antes de programar."},
    {n:"Variables, tipos de datos y operadores", d:"Una variable guarda un valor con un nombre; el tipo (número, texto, booleano) define qué se puede hacer con ella; los operadores la combinan."},
    {n:"Condiciones, ciclos y funciones", d:"Las condiciones deciden qué camino tomar, los ciclos repiten acciones, y las funciones agrupan código reutilizable."},
    {n:"Módulos y paquetes", d:"Un módulo es un archivo de código reutilizable; un paquete agrupa varios módulos ya hechos por otros para instalar y usar."},
    {n:"Manejo de errores", d:"Capturar errores (try/catch) permite responder con un mensaje claro en vez de que la aplicación se caiga."},
    {n:"Archivos, JSON, CSV y APIs", d:"Los programas leen y escriben datos en formatos estándar (JSON, CSV) y piden datos a otros sistemas mediante APIs."},
    {n:"Programación orientada a objetos", d:"Organiza el código en objetos que combinan datos y comportamiento, agrupados en clases reutilizables."},
    {n:"Programación funcional", d:"Trata el código como funciones que transforman datos sin modificar el estado original."},
    {n:"Código asíncrono", d:"Permite que un programa siga trabajando mientras espera algo lento, en vez de quedarse congelado."},
    {n:"Tipado", d:"Define si el tipo de una variable se revisa al escribir el código (estático) o al ejecutarlo (dinámico)."},
    {n:"Refactorización", d:"Es reescribir código para que sea más claro o eficiente, sin cambiar lo que hace desde afuera."},
    {n:"Buenas prácticas", d:"Nombres claros, funciones cortas y código consistente hacen un proyecto más fácil de mantener."},
], nota:"Se enseñaría primero un lenguaje principal, como Python o JavaScript, antes de mezclar varios.", preguntas:[
    {p:"¿Qué es un algoritmo?", o:["Un lenguaje de programación","Una secuencia ordenada de pasos para resolver un problema","Un tipo de variable","Un error de código"], c:1},
    {p:"¿Para qué sirve un ciclo (for/while)?", o:["Para decidir entre dos caminos","Para repetir una acción varias veces","Para guardar un valor","Para conectar a internet"], c:1},
    {p:"¿Qué hace un bloque try/catch?", o:["Repite código","Captura y maneja errores","Define una clase","Importa un paquete"], c:1},
    {p:"En programación orientada a objetos, ¿qué es una clase?", o:["Un archivo de configuración","Un molde que define datos y comportamiento de un objeto","Un tipo de ciclo","Un error común"], c:1},
    {p:"¿Qué ventaja tiene el código asíncrono?", o:["Hace el código más corto","Permite seguir trabajando mientras se espera algo lento","Elimina todos los errores","Convierte texto en números"], c:1},
    {p:"¿Qué es refactorizar?", o:["Borrar código","Reescribir código para que sea más claro, sin cambiar su comportamiento","Agregar nuevas funciones","Traducirlo a otro lenguaje"], c:1},
]},

{ id:3, titulo:"Estructuras de datos y algoritmos", temas:[
    {n:"Arreglos y cadenas", d:"Un arreglo guarda varios valores en orden bajo un nombre; una cadena es un arreglo de caracteres que forma texto."},
    {n:"Diccionarios y conjuntos", d:"Un diccionario guarda pares clave-valor para buscar por nombre; un conjunto guarda valores únicos, sin repetidos."},
    {n:"Pilas y colas", d:"Una pila atiende por el último que entró (LIFO); una cola por el primero que entró (FIFO), como una fila."},
    {n:"Listas enlazadas", d:"Guardan elementos conectados por referencias, en vez de estar uno junto al otro en memoria como un arreglo."},
    {n:"Árboles y grafos", d:"Un árbol organiza datos en niveles jerárquicos; un grafo conecta nodos entre sí sin jerarquía fija, como un mapa."},
    {n:"Búsqueda y ordenamiento", d:"Son algoritmos clásicos para encontrar un valor dentro de una colección o acomodarla en un orden específico."},
    {n:"Recursividad", d:"Es cuando una función se llama a sí misma para resolver versiones más pequeñas del mismo problema."},
    {n:"Backtracking", d:"Es probar un camino posible y, si no funciona, regresar y probar otro, hasta encontrar una solución válida."},
    {n:"Programación dinámica", d:"Resuelve problemas grandes guardando los resultados de subproblemas ya resueltos, para no recalcularlos."},
    {n:"Complejidad Big O", d:"Mide qué tan rápido crece el tiempo o la memoria que usa un algoritmo conforme crecen los datos."},
    {n:"Optimización y uso eficiente de memoria", d:"Consiste en elegir la estructura de datos y el algoritmo correctos para usar menos tiempo y recursos."},
], preguntas:[
    {p:"¿Qué estructura sigue \"el último que entra es el primero que sale\"?", o:["Cola","Pila","Árbol","Diccionario"], c:1},
    {p:"¿Qué es la recursividad?", o:["Repetir un ciclo infinito","Una función que se llama a sí misma para resolver un problema más pequeño","Ordenar una lista","Un tipo de error"], c:1},
    {p:"¿Qué mide la notación Big O?", o:["El número de líneas de código","Qué tan rápido crece el uso de tiempo o memoria de un algoritmo","La cantidad de variables","El lenguaje usado"], c:1},
    {p:"¿Qué guarda un diccionario?", o:["Solo números","Pares clave-valor","Solo texto","Nodos conectados"], c:1},
    {p:"¿Qué hace la programación dinámica?", o:["Ejecuta código en la nube","Guarda resultados de subproblemas para no recalcularlos","Ordena arreglos","Convierte tipos de datos"], c:1},
]},

{ id:4, titulo:"Desarrollo web", temas:[
    {n:"HTML semántico", d:"Usa etiquetas que describen el significado del contenido, no solo su apariencia, ayudando a accesibilidad y SEO."},
    {n:"CSS, Flexbox y Grid", d:"CSS define el estilo visual; Flexbox y Grid son sistemas para acomodar elementos en filas, columnas o cuadrículas."},
    {n:"Diseño responsive", d:"Hace que una página se vea y funcione bien en cualquier tamaño de pantalla, de celular a monitor grande."},
    {n:"JavaScript y TypeScript", d:"JavaScript da interactividad a una página; TypeScript es JavaScript con tipos, para detectar errores antes de ejecutar."},
    {n:"DOM, eventos y formularios", d:"El DOM es la representación en memoria de la página que JavaScript puede leer y modificar; los eventos reaccionan a acciones del usuario."},
    {n:"React, Vue, Angular u otro framework", d:"Organizan una aplicación web en componentes reutilizables, facilitando interfaces complejas."},
    {n:"Estado y componentes", d:"El estado es la información que cambia dentro de un componente y hace que la interfaz se actualice."},
    {n:"Aplicaciones progresivas", d:"Son sitios web que se pueden instalar como una app y funcionar incluso sin conexión."},
    {n:"Rendimiento web", d:"Qué tan rápido carga y responde una página, algo que afecta directamente la experiencia del usuario."},
    {n:"SEO básico", d:"Son las prácticas que ayudan a que un sitio aparezca mejor posicionado en los resultados de búsqueda."},
    {n:"Internacionalización", d:"Es preparar una aplicación para mostrar contenido en distintos idiomas y formatos regionales."},
    {n:"Accesibilidad y WCAG", d:"Son prácticas y estándares que aseguran que una página pueda ser usada por personas con discapacidades."},
], preguntas:[
    {p:"¿Qué hace el CSS en una página web?", o:["Define la estructura","Define el estilo visual","Maneja la base de datos","Define la lógica del servidor"], c:1},
    {p:"¿Qué es el DOM?", o:["Un lenguaje de programación","La representación en memoria de la página que JavaScript puede modificar","Un tipo de base de datos","Un framework"], c:1},
    {p:"¿Para qué sirve el diseño responsive?", o:["Para que la página cargue más rápido","Para que la página se vea bien en cualquier tamaño de pantalla","Para mejorar el SEO","Para cifrar datos"], c:1},
    {p:"¿Qué es una aplicación progresiva (PWA)?", o:["Una app que solo funciona en Android","Un sitio web que se puede instalar y funcionar sin conexión","Un tipo de base de datos","Un lenguaje nuevo"], c:1},
    {p:"¿Qué busca mejorar la accesibilidad web (WCAG)?", o:["La velocidad del servidor","Que la página pueda ser usada por personas con discapacidades","El diseño gráfico","El precio del hosting"], c:1},
]},

{ id:5, titulo:"Backend y APIs", temas:[
    {n:"Servidores", d:"Son computadoras (físicas o virtuales) que reciben peticiones y responden con datos o páginas por internet."},
    {n:"HTTP y códigos de respuesta", d:"HTTP es el protocolo con el que viajan las peticiones web; los códigos (200, 404, 500) indican qué pasó."},
    {n:"APIs REST", d:"Forma estándar de exponer datos y funciones de un servidor para que otras aplicaciones los consuman por HTTP."},
    {n:"GraphQL", d:"Alternativa a REST donde el cliente pide exactamente los datos que necesita, en una sola petición."},
    {n:"OpenAPI", d:"Formato estándar para documentar cómo funciona una API, para que otros sepan usarla sin adivinar."},
    {n:"JSON y serialización", d:"JSON es el formato más común para intercambiar datos; serializar convierte un objeto a ese formato."},
    {n:"Autenticación y autorización", d:"Autenticación confirma quién eres; autorización decide qué puedes hacer una vez identificado."},
    {n:"Sesiones, cookies y tokens", d:"Formas de recordar que un usuario ya inició sesión entre una petición y otra."},
    {n:"Roles y permisos", d:"Diferencian qué puede hacer cada tipo de usuario, como administrador o usuario normal."},
    {n:"Validación", d:"Es revisar que los datos que llegan a tu sistema sean correctos y seguros antes de usarlos."},
    {n:"Paginación y filtros", d:"Permiten mostrar y buscar grandes cantidades de datos en partes manejables."},
    {n:"WebSockets", d:"Conexiones que permiten comunicación en tiempo real entre cliente y servidor."},
    {n:"Webhooks", d:"Avisos automáticos que un sistema envía a otro cuando ocurre algo, sin que nadie pregunte."},
    {n:"Notificaciones", d:"Mensajes que se envían a un usuario para avisarle de algo, dentro o fuera de la app."},
    {n:"Trabajos en segundo plano", d:"Tareas que se ejecutan sin bloquear al usuario, como procesar un video o enviar un correo."},
    {n:"Límites de uso y caché", d:"Los límites evitan saturar un servicio; la caché guarda resultados ya calculados para responder más rápido."},
], preguntas:[
    {p:"¿Qué diferencia hay entre autenticación y autorización?", o:["Son lo mismo","Autenticación confirma quién eres, autorización qué puedes hacer","Autorización es el login","Autenticación define roles"], c:1},
    {p:"¿Qué formato se usa comúnmente para intercambiar datos entre sistemas?", o:["CSV únicamente","JSON","HTML","CSS"], c:1},
    {p:"¿Qué permite un WebSocket que una petición HTTP normal no?", o:["Guardar contraseñas","Comunicación en tiempo real, en ambos sentidos","Cifrar datos","Crear una base de datos"], c:1},
    {p:"¿Qué es un webhook?", o:["Un tipo de base de datos","Un aviso automático que un sistema envía a otro cuando pasa algo","Un framework de frontend","Un protocolo de red antiguo"], c:1},
    {p:"¿Para qué sirve la caché?", o:["Para cifrar contraseñas","Para responder más rápido guardando resultados ya calculados","Para validar formularios","Para crear sesiones"], c:1},
    {p:"¿Qué código HTTP indica que un recurso no fue encontrado?", o:["200","404","500","301"], c:1},
]},

{ id:6, titulo:"Bases de datos", temas:[
    {n:"Modelado de información", d:"Diseñar cómo se van a organizar los datos antes de guardarlos, pensando en entidades y relaciones."},
    {n:"SQL", d:"Lenguaje estándar para consultar y modificar datos en una base de datos relacional."},
    {n:"PostgreSQL o MySQL", d:"Sistemas de bases de datos relacionales muy usados para guardar datos estructurados en tablas."},
    {n:"Relaciones y claves", d:"Las claves identifican de forma única cada registro y permiten relacionar tablas entre sí."},
    {n:"Normalización", d:"Organizar los datos para evitar repetirlos innecesariamente, reduciendo inconsistencias."},
    {n:"Consultas y joins", d:"Las consultas piden datos a la base; los joins combinan información de varias tablas relacionadas."},
    {n:"Índices", d:"Estructuras que aceleran la búsqueda de datos, a cambio de un poco más de espacio."},
    {n:"Transacciones", d:"Agrupan operaciones para que se completen todas juntas o ninguna."},
    {n:"Migraciones", d:"Cambios controlados y versionados en la estructura de la base de datos."},
    {n:"Respaldos", d:"Copias de seguridad de los datos, necesarias para recuperarse de un error o pérdida."},
    {n:"Redis y caché", d:"Redis es una base de datos en memoria, muy rápida, usada para cachear datos o manejar sesiones."},
    {n:"MongoDB y NoSQL", d:"Bases de datos que no usan tablas fijas, sino documentos flexibles."},
    {n:"Cuándo usar cada tipo de base de datos", d:"Depende de si los datos son muy estructurados (relacional) o flexibles (NoSQL), y de la velocidad o consistencia necesaria."},
], preguntas:[
    {p:"¿Qué lenguaje se usa para consultar bases de datos relacionales?", o:["HTML","SQL","CSS","JSON"], c:1},
    {p:"¿Qué hace un \"join\" en SQL?", o:["Borra una tabla","Combina datos de varias tablas relacionadas","Crea una copia de seguridad","Cifra los datos"], c:1},
    {p:"¿Para qué sirve una transacción en una base de datos?", o:["Para acelerar las búsquedas","Para que varias operaciones se completen todas juntas o ninguna","Para borrar datos duplicados","Para crear índices"], c:1},
    {p:"¿Qué caracteriza a una base de datos NoSQL como MongoDB?", o:["Usa siempre tablas fijas","Guarda datos en documentos flexibles, sin estructura fija","No permite consultas","Solo funciona en memoria"], c:1},
    {p:"¿Para qué sirven los índices en una base de datos?", o:["Para cifrar información","Para acelerar la búsqueda de datos","Para hacer respaldos","Para definir permisos"], c:1},
]},

{ id:7, titulo:"Ingeniería de software", temas:[
    {n:"Análisis de requisitos", d:"Entender exactamente qué necesita resolver el software antes de empezar a construirlo."},
    {n:"Diseño de sistemas", d:"Planear cómo se van a conectar las distintas partes de una aplicación antes de programarlas."},
    {n:"Arquitectura de aplicaciones", d:"Define la estructura general del software: cómo se organiza en capas o servicios."},
    {n:"Código limpio", d:"Escribir código fácil de leer y entender, con nombres claros y funciones simples."},
    {n:"Principios SOLID", d:"Cinco reglas de diseño orientado a objetos que ayudan a mantener y extender el código más fácilmente."},
    {n:"Separación de responsabilidades", d:"Cada parte del código debería encargarse de una sola cosa."},
    {n:"Patrones de diseño", d:"Soluciones ya probadas para problemas comunes de diseño de software."},
    {n:"Refactorización", d:"Mejorar la estructura interna del código sin cambiar lo que hace desde afuera."},
    {n:"Deuda técnica", d:"Atajos tomados para entregar más rápido que, si no se corrigen, complican el mantenimiento futuro."},
    {n:"Documentación", d:"Explicar cómo funciona y cómo se usa el software, para otros o para tu propio yo futuro."},
    {n:"Mantenibilidad", d:"Qué tan fácil es modificar o corregir un sistema sin romper otras partes."},
    {n:"Escalabilidad", d:"Capacidad de un sistema de seguir funcionando bien cuando crece la cantidad de usuarios o datos."},
    {n:"Monolitos modulares", d:"Aplicaciones que corren como una sola unidad, pero organizadas internamente en módulos separados."},
    {n:"Microservicios", d:"Dividen una aplicación en servicios pequeños e independientes que se comunican entre sí."},
    {n:"Sistemas orientados a eventos", d:"Se emiten eventos que otros sistemas escuchan y a los que reaccionan de forma independiente."},
], preguntas:[
    {p:"¿Qué es la deuda técnica?", o:["Un préstamo bancario","Los atajos que, si no se corrigen, dificultan mantener el código con el tiempo","Un tipo de base de datos","Un error de sintaxis"], c:1},
    {p:"¿Qué buscan los principios SOLID?", o:["Acelerar internet","Que el código orientado a objetos sea más fácil de mantener y extender","Diseñar interfaces gráficas","Comprimir archivos"], c:1},
    {p:"¿Qué caracteriza a los microservicios?", o:["Toda la app corre como una sola unidad","La app se divide en servicios pequeños e independientes","No usan bases de datos","Solo sirven para apps móviles"], c:1},
    {p:"¿Qué es refactorizar código?", o:["Agregar nuevas funciones","Mejorar su estructura interna sin cambiar lo que hace","Borrarlo por completo","Traducirlo a otro lenguaje"], c:1},
    {p:"¿Qué mide la escalabilidad de un sistema?", o:["Qué tan bonito se ve","Su capacidad de seguir funcionando bien cuando crecen los usuarios o datos","Cuántos colores usa","El nombre de las variables"], c:1},
]},

{ id:8, titulo:"Git y trabajo colaborativo", temas:[
    {n:"Git desde cero", d:"Sistema de control de versiones que guarda el historial de cambios de un proyecto."},
    {n:"Repositorios", d:"Las carpetas de proyecto donde Git guarda todo el historial de cambios."},
    {n:"Ramas", d:"Permiten trabajar en una versión paralela del código sin afectar la versión principal."},
    {n:"Commits", d:"\"Fotos\" guardadas del estado del código en un momento, con un mensaje que explica qué cambió."},
    {n:"Pull requests", d:"Propuestas para integrar los cambios de una rama a otra, normalmente revisadas antes de aceptarse."},
    {n:"Merge y rebase", d:"Dos formas distintas de combinar el historial de una rama con otra."},
    {n:"Resolución de conflictos", d:"Ocurre cuando dos cambios chocan entre sí y hay que decidir manualmente cuál se queda."},
    {n:"Code review", d:"Cuando otra persona revisa tu código antes de integrarlo, buscando errores o mejoras."},
    {n:"Issues", d:"Tickets para reportar errores o proponer mejoras dentro de un proyecto."},
    {n:"Tableros de proyectos", d:"Organizan visualmente las tareas pendientes, en progreso y terminadas de un equipo."},
    {n:"Releases y etiquetas", d:"Marcan versiones específicas del proyecto publicadas."},
    {n:"README profesionales", d:"El archivo que explica qué es el proyecto, cómo instalarlo y cómo usarlo."},
    {n:"Licencias", d:"Definen legalmente qué puede hacer otra persona con tu código."},
    {n:"Protección de claves y secretos", d:"Prácticas para evitar que contraseñas o llaves terminen expuestas en un repositorio."},
], preguntas:[
    {p:"¿Qué es un commit en Git?", o:["Una rama nueva","Una \"foto\" guardada del código en un momento con un mensaje que explica el cambio","Un tipo de licencia","Un error de programación"], c:1},
    {p:"¿Para qué sirven las ramas en Git?", o:["Para borrar el historial","Para trabajar en una versión paralela sin afectar la principal","Para cifrar el código","Para hacer respaldos"], c:1},
    {p:"¿Qué es un pull request?", o:["Un tipo de base de datos","Una propuesta para integrar cambios de una rama a otra, normalmente revisada por otros","Un comando para borrar archivos","Un servidor"], c:1},
    {p:"¿Qué es el code review?", o:["Revisar el código de otra persona antes de integrarlo","Borrar código viejo","Comprimir un repositorio","Crear una licencia"], c:0},
    {p:"¿Por qué es importante proteger claves y secretos en un repositorio?", o:["Para que el código corra más rápido","Para evitar que queden expuestos y alguien los use sin permiso","Para mejorar el diseño","Para reducir el tamaño del proyecto"], c:1},
]},

{ id:9, titulo:"Pruebas y calidad", temas:[
    {n:"Pruebas manuales", d:"Usar la aplicación a mano para verificar que funcione como se espera."},
    {n:"Pruebas unitarias", d:"Verifican automáticamente que una pieza pequeña de código haga exactamente lo que debe."},
    {n:"Pruebas de integración", d:"Verifican que varias partes del sistema funcionen bien juntas, no solo por separado."},
    {n:"Pruebas de extremo a extremo", d:"Simulan el flujo completo de un usuario real, de principio a fin."},
    {n:"Pruebas de aceptación", d:"Confirman que el sistema cumple con lo que el negocio o cliente pidió."},
    {n:"Mocks, stubs y fakes", d:"Versiones simuladas de partes del sistema, usadas durante pruebas para no depender de ellas de verdad."},
    {n:"Pruebas de seguridad", d:"Buscan vulnerabilidades que alguien podría aprovechar para atacar el sistema."},
    {n:"Pruebas de rendimiento", d:"Miden qué tan rápido responde el sistema y cuánta carga puede soportar."},
    {n:"Pruebas de accesibilidad", d:"Verifican que la aplicación pueda ser usada por personas con distintas capacidades."},
    {n:"Cobertura de código", d:"Mide qué porcentaje del código está realmente cubierto por pruebas automáticas."},
    {n:"Integración continua", d:"Ejecutar pruebas automáticamente cada vez que alguien sube cambios."},
    {n:"Regresión y control de calidad", d:"Las pruebas de regresión verifican que un cambio nuevo no haya roto algo que ya funcionaba."},
], preguntas:[
    {p:"¿Qué verifica una prueba unitaria?", o:["Todo el sistema completo","Que una pieza pequeña de código haga exactamente lo que debe","La velocidad del servidor","El diseño visual"], c:1},
    {p:"¿Para qué se usan los mocks en pruebas?", o:["Para simular partes del sistema sin depender de ellas de verdad","Para borrar código","Para medir el rendimiento","Para documentar el proyecto"], c:0},
    {p:"¿Qué busca una prueba de regresión?", o:["Mejorar el diseño","Verificar que un cambio nuevo no haya roto algo que ya funcionaba","Medir la cobertura","Simular usuarios falsos"], c:1},
    {p:"¿Qué es la integración continua?", o:["Ejecutar pruebas automáticamente cada vez que se sube código nuevo","Un tipo de base de datos","Un lenguaje de programación","Una forma de diseño gráfico"], c:0},
    {p:"¿Qué mide la cobertura de código?", o:["La velocidad de carga","Qué porcentaje del código está cubierto por pruebas automáticas","El número de usuarios","El tamaño del archivo"], c:1},
]},

{ id:10, titulo:"Seguridad", temas:[
    {n:"Contraseñas seguras", d:"Largas, únicas por servicio y difíciles de adivinar, idealmente generadas con un gestor de contraseñas."},
    {n:"Hashing", d:"Convierte una contraseña en un valor irreversible que se guarda en vez de la original."},
    {n:"Autenticación multifactor", d:"Pide un segundo factor además de la contraseña para confirmar que de verdad eres tú."},
    {n:"Control de acceso", d:"Define quién puede ver o hacer qué dentro de un sistema."},
    {n:"Inyección SQL", d:"Ataque donde alguien mete código SQL malicioso a través de un formulario para manipular la base de datos."},
    {n:"XSS", d:"Ataque donde se inyecta código malicioso que se ejecuta en el navegador de otros usuarios."},
    {n:"CSRF", d:"Engaña al navegador de un usuario ya autenticado para que haga una acción sin que se dé cuenta."},
    {n:"SSRF", d:"Obliga al servidor a hacer peticiones a lugares internos que no debería poder alcanzar."},
    {n:"IDOR", d:"Ocurre cuando un sistema no verifica bien los permisos y un usuario accede a datos de otro cambiando un identificador."},
    {n:"Subida segura de archivos", d:"Validar y restringir qué archivos se pueden subir, para evitar que alguien suba algo malicioso."},
    {n:"CORS", d:"Política del navegador que controla qué sitios pueden hacer peticiones a tu servidor desde otro dominio."},
    {n:"Encabezados de seguridad", d:"Configuraciones HTTP que protegen contra ataques comunes, como forzar HTTPS."},
    {n:"Cifrado", d:"Convierte información en un formato ilegible sin la clave correcta."},
    {n:"Gestión de secretos", d:"Prácticas para guardar claves y contraseñas fuera del código, en lugares seguros."},
    {n:"Privacidad", d:"Proteger los datos personales de los usuarios y usarlos solo para lo que aceptaron."},
    {n:"OWASP", d:"Organización que publica la lista de los riesgos de seguridad más comunes en apps web."},
    {n:"Modelado de amenazas", d:"Pensar de antemano cómo podrían atacar tu sistema, para diseñar defensas antes de que pase."},
    {n:"Respuesta ante incidentes", d:"El plan de qué hacer cuando ya ocurrió un problema de seguridad, para contenerlo y resolverlo rápido."},
], preguntas:[
    {p:"¿Qué hace el hashing con una contraseña?", o:["La cifra para poder recuperarla después","La convierte en un valor irreversible que se guarda en vez del original","La borra","La comparte con otros servicios"], c:1},
    {p:"¿Qué es un ataque de inyección SQL?", o:["Meter código SQL malicioso a través de un formulario para manipular la base de datos","Un virus de computadora","Un tipo de contraseña","Un protocolo de red"], c:0},
    {p:"¿Qué es XSS?", o:["Un tipo de base de datos","Inyectar código malicioso que se ejecuta en el navegador de otros usuarios","Un método de cifrado","Un gestor de contraseñas"], c:1},
    {p:"¿Para qué sirve la autenticación multifactor?", o:["Para hacer el login más lento","Para pedir un segundo factor además de la contraseña y confirmar que eres tú","Para cifrar archivos","Para bloquear IPs"], c:1},
    {p:"¿Qué controla CORS?", o:["La velocidad del servidor","Qué sitios pueden hacer peticiones a tu servidor desde otro dominio","El diseño de la página","El tamaño de los archivos"], c:1},
    {p:"¿Qué es OWASP?", o:["Un lenguaje de programación","Una organización que publica los riesgos de seguridad más comunes en apps web","Un framework de frontend","Un tipo de base de datos"], c:1},
]},

{ id:11, titulo:"Cloud y DevOps", temas:[
    {n:"Servidores Linux", d:"La base más común para alojar aplicaciones en internet, por su estabilidad y control."},
    {n:"Docker", d:"Empaqueta una aplicación con todo lo que necesita para correr igual en cualquier máquina."},
    {n:"Contenedores", d:"Instancias ligeras y aisladas donde corre una aplicación empaquetada."},
    {n:"CI/CD", d:"Automatiza probar (integración continua) y desplegar (entrega continua) el código con cada cambio."},
    {n:"GitHub Actions", d:"Herramienta para automatizar tareas, como pruebas o despliegues, desde un repositorio de GitHub."},
    {n:"Infraestructura como código", d:"Define servidores y recursos en la nube mediante archivos de configuración."},
    {n:"Servicios cloud", d:"Recursos de cómputo, almacenamiento o red rentados bajo demanda a proveedores como AWS, Azure o Google Cloud."},
    {n:"Bases de datos administradas", d:"Bases de datos que un proveedor cloud mantiene, respalda y actualiza por ti."},
    {n:"Almacenamiento", d:"Dónde y cómo se guardan archivos y datos de forma duradera en la nube."},
    {n:"Redes y permisos", d:"Definen qué partes de tu infraestructura pueden comunicarse y quién tiene acceso."},
    {n:"Dominios y certificados HTTPS", d:"El dominio es el nombre de tu sitio; el certificado HTTPS cifra la conexión a él."},
    {n:"Logs", d:"Registros de lo que va pasando dentro de un sistema, útiles para entender errores después."},
    {n:"Métricas", d:"Números medidos con el tiempo (uso de CPU, peticiones) que muestran el estado de un sistema."},
    {n:"Trazas", d:"Siguen el camino completo de una petición a través de varios servicios."},
    {n:"Monitoreo", d:"Observar continuamente el estado de un sistema para detectar problemas."},
    {n:"Alertas", d:"Avisan automáticamente cuando algo sale de lo normal."},
    {n:"Backups", d:"Copias de seguridad periódicas para poder recuperar datos si algo sale mal."},
    {n:"Recuperación ante fallos", d:"El plan y las herramientas para volver a poner un sistema en funcionamiento tras una falla."},
    {n:"Kubernetes básico", d:"Administra automáticamente muchos contenedores: cuántos correr, dónde, y qué hacer si uno falla."},
    {n:"Control de costos", d:"Vigilar y optimizar cuánto se gasta en recursos cloud."},
], preguntas:[
    {p:"¿Qué hace Docker?", o:["Escribe código automáticamente","Empaqueta una app con todo lo que necesita para correr igual en cualquier máquina","Diseña interfaces","Cifra contraseñas"], c:1},
    {p:"¿Qué automatiza CI/CD?", o:["El diseño gráfico","Probar y desplegar el código automáticamente con cada cambio","La gestión de contraseñas","La creación de bases de datos"], c:1},
    {p:"¿Qué es infraestructura como código?", o:["Escribir servidores a mano cada vez","Definir servidores y recursos cloud mediante archivos de configuración","Un lenguaje de programación","Un tipo de base de datos"], c:1},
    {p:"¿Para qué sirven las métricas en producción?", o:["Para diseñar la interfaz","Para medir con el tiempo cosas como el uso de CPU o peticiones","Para cifrar datos","Para hacer pruebas unitarias"], c:1},
    {p:"¿Qué gestiona Kubernetes?", o:["Bases de datos relacionales","Muchos contenedores: cuántos correr, dónde, y qué hacer si uno falla","El diseño responsive","Los certificados HTTPS"], c:1},
    {p:"¿Para qué sirven los backups?", o:["Para acelerar el sitio","Para tener copias de seguridad y poder recuperar datos si algo sale mal","Para medir el rendimiento","Para automatizar despliegues"], c:1},
]},

{ id:12, titulo:"Aplicaciones móviles", temas:[
    {n:"Android", d:"El sistema operativo móvil de Google, el más usado en el mundo."},
    {n:"Kotlin", d:"El lenguaje moderno recomendado para desarrollar aplicaciones nativas de Android."},
    {n:"iOS y Swift", d:"iOS es el sistema operativo móvil de Apple; Swift es el lenguaje para sus apps nativas."},
    {n:"Flutter o React Native", d:"Frameworks que permiten escribir una sola base de código y generar apps para Android e iOS."},
    {n:"Interfaces táctiles", d:"Diseñadas para interactuar con gestos como tocar, deslizar o pellizcar la pantalla."},
    {n:"Ciclo de vida móvil", d:"Los distintos estados por los que pasa una app (abierta, en segundo plano, cerrada)."},
    {n:"Uso sin conexión", d:"Diseñar una app para que siga funcionando, al menos parcialmente, sin internet."},
    {n:"Notificaciones push", d:"Mensajes que llegan al dispositivo incluso cuando la app no está abierta."},
    {n:"Cámara y ubicación", d:"Funciones del dispositivo que una app puede usar con el permiso del usuario."},
    {n:"Almacenamiento local", d:"Guardar datos directamente en el dispositivo, para tenerlos rápido o sin internet."},
    {n:"Permisos", d:"Autorizaciones explícitas que el usuario da para acceder a cámara, ubicación o contactos."},
    {n:"Publicación en tiendas", d:"El proceso de subir una app a Google Play o la App Store."},
    {n:"Firmas y actualizaciones", d:"Firmar certifica quién publicó la app; las actualizaciones entregan mejoras sin reinstalar todo."},
    {n:"Accesibilidad móvil", d:"Prácticas para que una app móvil pueda ser usada por personas con distintas capacidades."},
], preguntas:[
    {p:"¿Qué lenguaje se usa comúnmente para apps nativas de Android?", o:["Swift","Kotlin","PHP","Ruby"], c:1},
    {p:"¿Qué ventaja ofrecen Flutter o React Native?", o:["Solo funcionan en iOS","Permiten escribir una sola base de código para Android e iOS","Eliminan la necesidad de diseño","Son bases de datos"], c:1},
    {p:"¿Qué son las notificaciones push?", o:["Mensajes que llegan al dispositivo incluso cuando la app no está abierta","Un tipo de base de datos","Un permiso del sistema","Un lenguaje de programación"], c:0},
    {p:"¿Para qué se piden permisos en una app móvil?", o:["Para cobrar al usuario","Para autorizar el acceso a cosas como cámara, ubicación o contactos","Para publicarla en la tienda","Para firmarla"], c:1},
    {p:"¿Qué certifica la firma de una aplicación?", o:["Su velocidad","Quién la publicó","Su diseño","Su precio"], c:1},
]},

{ id:13, titulo:"Aplicaciones de escritorio", temas:[
    {n:"Interfaces nativas", d:"Construidas con las herramientas propias de cada sistema operativo."},
    {n:"Electron, Tauri, .NET o Qt", d:"Tecnologías para construir aplicaciones de escritorio, con distintos balances entre rendimiento y facilidad."},
    {n:"Menús y atajos", d:"Elementos de navegación clásicos, junto con combinaciones de teclas para acciones rápidas."},
    {n:"Archivos locales", d:"Leer y escribir archivos directamente en el sistema del usuario."},
    {n:"Bases de datos locales", d:"Guardan datos directamente en la computadora del usuario, sin servidor externo."},
    {n:"Instaladores", d:"Paquetes que permiten instalar la aplicación fácilmente."},
    {n:"Actualizaciones automáticas", d:"Permiten que la app se actualice sola, sin reinstalación manual."},
    {n:"Firma de aplicaciones", d:"Certifica que el instalador no fue modificado por alguien más."},
    {n:"Seguridad entre procesos", d:"Asegura que las partes internas de la app no puedan explotarse entre sí."},
    {n:"Compatibilidad con Windows, macOS y Linux", d:"Diseñar la app para que funcione correctamente en los distintos sistemas de escritorio."},
], preguntas:[
    {p:"¿Qué permite Electron o Tauri?", o:["Crear apps móviles nativas","Construir aplicaciones de escritorio","Diseñar bases de datos","Crear APIs REST"], c:1},
    {p:"¿Qué hace un instalador?", o:["Ejecuta pruebas automáticas","Permite instalar la aplicación fácilmente en el sistema del usuario","Cifra los datos","Conecta a internet"], c:1},
    {p:"¿Para qué sirve la firma de una app de escritorio?", o:["Para hacerla más rápida","Para certificar que el instalador no fue modificado por alguien más","Para traducirla","Para comprimirla"], c:1},
    {p:"¿Qué ventaja tiene una base de datos local?", o:["Necesita internet siempre","Guarda datos directamente en la computadora del usuario, sin servidor externo","Es más lenta siempre","No se puede usar en apps de escritorio"], c:1},
    {p:"¿Qué buscan las actualizaciones automáticas?", o:["Que el usuario reinstale manualmente","Que la app se actualice sola sin intervención manual","Que la app deje de funcionar","Que se desinstale"], c:1},
]},

{ id:14, titulo:"Datos e inteligencia artificial", temas:[
    {n:"Python para datos", d:"El lenguaje más usado para trabajar con datos, por su simplicidad y librerías especializadas."},
    {n:"NumPy y pandas", d:"NumPy maneja cálculos numéricos eficientes; pandas organiza y manipula datos en tablas."},
    {n:"SQL para análisis", d:"Permite consultar y resumir grandes cantidades de datos desde una base de datos."},
    {n:"Limpieza de datos", d:"Corregir o eliminar datos incorrectos, duplicados o incompletos antes de analizarlos."},
    {n:"Visualización", d:"Convierte datos en gráficas para que sus patrones sean más fáciles de entender."},
    {n:"Estadística", d:"Herramientas para resumir y entender datos: promedios, distribuciones, correlaciones."},
    {n:"Probabilidad", d:"Estudia qué tan posible es que ocurra un evento, base de muchos modelos."},
    {n:"Álgebra lineal", d:"Trabaja con vectores y matrices, la estructura sobre la que se construyen los modelos de machine learning."},
    {n:"Cálculo y gradientes", d:"Las derivadas permiten que los modelos \"aprendan\" ajustando sus parámetros poco a poco."},
    {n:"Machine learning", d:"Algoritmos que aprenden patrones a partir de datos, en vez de seguir reglas escritas a mano."},
    {n:"Regresión", d:"Predice un valor numérico continuo, como el precio de una casa."},
    {n:"Clasificación", d:"Predice una categoría, como si un correo es spam o no."},
    {n:"Clustering", d:"Agrupa datos parecidos entre sí sin categorías predefinidas."},
    {n:"Detección de anomalías", d:"Identifica datos que se salen mucho de lo normal, útil para fraudes o fallas."},
    {n:"Validación de modelos", d:"Comprobar qué tan bien funciona un modelo con datos que no vio durante su entrenamiento."},
    {n:"Métricas", d:"Formas numéricas de medir qué tan bueno es un modelo, como precisión o error promedio."},
    {n:"Sesgo y sobreajuste", d:"El sesgo es un modelo demasiado simple; el sobreajuste es cuando memoriza los datos en vez de aprender el patrón."},
    {n:"Redes neuronales", d:"Modelos inspirados en el cerebro, formados por capas de unidades conectadas que ajustan sus pesos."},
    {n:"Deep learning", d:"Usa redes neuronales con muchas capas para aprender patrones complejos directamente de los datos."},
    {n:"Visión artificial", d:"Rama de la IA que permite a una computadora interpretar imágenes y video."},
    {n:"Procesamiento de lenguaje natural", d:"Permite que una computadora entienda y genere texto en lenguaje humano."},
    {n:"Transformers", d:"Arquitectura de red neuronal detrás de los modelos de lenguaje modernos."},
    {n:"Modelos de lenguaje", d:"Modelos entrenados para predecir y generar texto, la base de asistentes como Claude."},
    {n:"IA generativa", d:"Modelos que crean contenido nuevo (texto, imágenes, audio) en vez de solo clasificar o predecir."},
    {n:"Embeddings", d:"Convierten palabras, frases o imágenes en vectores numéricos que capturan su significado."},
    {n:"Bases vectoriales", d:"Guardan esos embeddings y permiten buscar rápidamente los más parecidos a una consulta."},
    {n:"RAG", d:"Combina un modelo de lenguaje con búsqueda de información externa, para responder con datos actualizados."},
    {n:"Fine-tuning", d:"Ajustar un modelo ya entrenado con datos adicionales para especializarlo en una tarea concreta."},
    {n:"Agentes y herramientas", d:"Sistemas de IA que pueden usar herramientas externas para completar tareas más allá de responder texto."},
    {n:"MLOps", d:"Prácticas para llevar modelos de machine learning de forma confiable a producción."},
    {n:"Evaluación de modelos", d:"Medir de forma rigurosa qué tan bien funciona un modelo antes de confiar en él."},
    {n:"Costos y rendimiento", d:"Balancear qué tan preciso es un modelo contra cuánto cuesta entrenarlo y usarlo."},
], preguntas:[
    {p:"¿Qué hace pandas en Python?", o:["Entrena redes neuronales","Organiza y manipula datos en tablas","Diseña interfaces web","Cifra contraseñas"], c:1},
    {p:"¿Qué diferencia hay entre regresión y clasificación?", o:["Son lo mismo","Regresión predice un número, clasificación predice una categoría","Clasificación predice un número","Regresión solo funciona con imágenes"], c:1},
    {p:"¿Qué es el sobreajuste (overfitting)?", o:["Un modelo demasiado simple","Un modelo que memoriza los datos de entrenamiento en vez de aprender el patrón general","Un error de sintaxis","Un tipo de red neuronal"], c:1},
    {p:"¿Qué son los embeddings?", o:["Bases de datos relacionales","Vectores numéricos que capturan el significado de palabras, frases o imágenes","Un lenguaje de programación","Un tipo de gráfica"], c:1},
    {p:"¿Qué hace RAG (retrieval-augmented generation)?", o:["Entrena modelos desde cero","Combina un modelo de lenguaje con búsqueda de información externa para responder mejor","Solo genera imágenes","Elimina la necesidad de datos"], c:1},
    {p:"¿Qué es el fine-tuning?", o:["Borrar un modelo","Ajustar un modelo ya entrenado con datos adicionales para especializarlo","Medir el rendimiento del servidor","Visualizar datos"], c:1},
    {p:"¿Qué estudia el machine learning?", o:["El diseño de páginas web","Algoritmos que aprenden patrones a partir de datos","Solo bases de datos SQL","La seguridad de redes"], c:1},
]},

{ id:15, titulo:"IA responsable", temas:[
    {n:"Privacidad", d:"Proteger los datos personales que un modelo de IA pudo haber usado o pudiera exponer."},
    {n:"Sesgos", d:"Patrones injustos que un modelo puede aprender si los datos con los que se entrenó ya los contenían."},
    {n:"Transparencia", d:"Ser claro sobre cómo funciona un sistema de IA y qué datos usó."},
    {n:"Explicabilidad", d:"Entender por qué un modelo dio una respuesta específica, no solo cuál fue."},
    {n:"Seguridad de modelos", d:"Proteger un modelo de IA de ser manipulado, robado o usado de forma maliciosa."},
    {n:"Inyección de prompts", d:"Ataque donde alguien intenta manipular las instrucciones de un modelo con texto diseñado para eso."},
    {n:"Fuga de información", d:"Cuando un modelo revela sin querer datos sensibles con los que fue entrenado o que tuvo en su contexto."},
    {n:"Datos contaminados", d:"Datos de entrenamiento con información falsa, maliciosa o de mala calidad que afecta el modelo."},
    {n:"Derechos de autor", d:"Respetar la propiedad intelectual del contenido usado o generado por un modelo de IA."},
    {n:"Uso ético", d:"Pensar en el impacto real que tendrá un sistema de IA en las personas antes de desplegarlo."},
    {n:"Supervisión humana", d:"Mantener a una persona en control o revisando las decisiones importantes de un sistema de IA."},
    {n:"Documentación de modelos", d:"Registrar cómo se entrenó un modelo, con qué datos y con qué limitaciones."},
    {n:"Evaluación de riesgos", d:"Identificar de antemano qué podría salir mal con un sistema de IA y qué tan grave sería."},
    {n:"Plan de respuesta ante errores", d:"Tener definido qué hacer cuando un sistema de IA falla o se comporta de forma inesperada."},
], preguntas:[
    {p:"¿Qué es un sesgo en un modelo de IA?", o:["Un error de sintaxis","Un patrón injusto aprendido de los datos de entrenamiento","Un tipo de red neuronal","Un protocolo de seguridad"], c:1},
    {p:"¿Qué es la inyección de prompts?", o:["Un tipo de entrenamiento","Un ataque que intenta manipular las instrucciones de un modelo con texto diseñado para eso","Una métrica de rendimiento","Un tipo de base de datos"], c:1},
    {p:"¿Qué busca la explicabilidad en IA?", o:["Que el modelo sea más rápido","Entender por qué un modelo dio una respuesta específica","Reducir el costo del modelo","Aumentar los datos de entrenamiento"], c:1},
    {p:"¿Por qué es importante la supervisión humana en sistemas de IA?", o:["Para hacerlos más lentos","Para mantener a una persona en control de decisiones importantes","Para entrenarlos más rápido","Para reducir su tamaño"], c:1},
    {p:"¿Qué es la fuga de información en un modelo?", o:["Cuando el servidor se cae","Cuando el modelo revela sin querer datos sensibles de su entrenamiento o contexto","Cuando el modelo tarda mucho en responder","Cuando el modelo se actualiza"], c:1},
]},

{ id:16, titulo:"Proyectos reales", nota:"Los alumnos deberían construir, entre otros, estos proyectos.", temas:[
    {n:"Aplicación de consola", d:"Un programa que se usa completamente desde la terminal, ideal para practicar lógica y manejo de entradas y salidas."},
    {n:"Página personal", d:"Un sitio simple con HTML y CSS que presenta quién eres, tus proyectos y cómo contactarte."},
    {n:"Blog", d:"Un sitio donde se publican artículos, generalmente con un sistema para crear, editar y organizar publicaciones."},
    {n:"Tienda en línea", d:"Un sistema con catálogo de productos, carrito de compras y proceso de pago."},
    {n:"Sistema de usuarios", d:"Registro, inicio de sesión y gestión de perfiles, la base de casi cualquier app con cuentas."},
    {n:"API con base de datos", d:"Un backend que expone datos a través de endpoints, conectado a una base de datos real."},
    {n:"Chat en tiempo real", d:"Una app de mensajería que usa WebSockets para que los mensajes lleguen al instante."},
    {n:"Aplicación móvil", d:"Una app funcional para Android o iOS, o ambas con un framework multiplataforma."},
    {n:"Aplicación de escritorio", d:"Un programa instalable que corre directamente en la computadora del usuario."},
    {n:"Sistema de inventario", d:"Una herramienta para llevar el control de productos, cantidades y movimientos de stock."},
    {n:"Plataforma educativa", d:"Un sistema para organizar cursos, lecciones y seguimiento de progreso, como esta misma sección de MichiHub."},
    {n:"Proyecto colaborativo", d:"Un proyecto trabajado en equipo usando Git, con ramas, pull requests y revisión de código."},
    {n:"Asistente con IA", d:"Una aplicación que usa un modelo de lenguaje para responder preguntas o automatizar tareas."},
    {n:"Sistema de análisis de datos", d:"Una herramienta que procesa datos reales y muestra resultados en gráficas o reportes."},
    {n:"Proyecto final desplegado y documentado", d:"Un proyecto completo, publicado en internet y con documentación clara de cómo funciona."},
], preguntas:[
    {p:"¿Por qué es importante documentar un proyecto?", o:["Para que se vea más largo","Para que otros (y tu propio yo futuro) entiendan cómo funciona y cómo usarlo","Para ocupar más espacio","Para que cargue más rápido"], c:1},
    {p:"¿Qué significa que un proyecto esté \"desplegado\"?", o:["Que está guardado solo en tu computadora","Que está publicado y accesible en internet","Que tiene muchas líneas de código","Que fue revisado por otra persona"], c:1},
    {p:"¿Qué aporta trabajar un proyecto de forma colaborativa con Git?", o:["Nada distinto a trabajar solo","Practicar ramas, pull requests y revisión de código en equipo","Hacer el proyecto más lento","Evitar usar control de versiones"], c:1},
    {p:"¿Qué caracteriza a una API con base de datos?", o:["Solo tiene diseño visual","Expone datos a través de endpoints, conectada a una base de datos real","No necesita servidor","Es siempre una app móvil"], c:1},
    {p:"¿Qué distingue a un chat en tiempo real de un formulario normal?", o:["Usa WebSockets para que los mensajes lleguen al instante","No necesita servidor","Solo funciona sin internet","No se puede probar"], c:0},
]},

{ id:17, titulo:"Habilidades profesionales", temas:[
    {n:"Comunicación técnica", d:"Explicar ideas o problemas técnicos de forma clara, adaptando el nivel de detalle según quién te escucha."},
    {n:"Trabajo en equipo", d:"Colaborar de forma efectiva con otras personas hacia un objetivo común."},
    {n:"Inglés técnico", d:"Gran parte de la documentación y comunidad de programación está en inglés."},
    {n:"Metodologías ágiles", d:"Formas de organizar el trabajo en ciclos cortos, con entregas frecuentes y ajustes constantes."},
    {n:"Scrum y Kanban", d:"Scrum organiza el trabajo en sprints con roles definidos; Kanban visualiza el flujo en un tablero continuo."},
    {n:"Organización de tareas", d:"Dividir el trabajo en partes manejables y darles prioridad."},
    {n:"Estimación de tiempos", d:"Calcular cuánto tiempo tomará una tarea, una habilidad que mejora con la práctica."},
    {n:"Reporte de avances", d:"Comunicar claramente qué se ha hecho, qué falta y qué obstáculos hay."},
    {n:"Presentaciones", d:"Mostrar tu trabajo de forma clara y convincente frente a otras personas."},
    {n:"Lectura de documentación", d:"Saber buscar y entender la documentación oficial de una herramienta."},
    {n:"Code review", d:"Dar y recibir retroalimentación sobre código de forma constructiva."},
    {n:"Resolución de conflictos", d:"Manejar desacuerdos dentro de un equipo de forma profesional."},
    {n:"Pensamiento crítico", d:"Cuestionar suposiciones y evaluar evidencia antes de tomar una decisión técnica."},
], preguntas:[
    {p:"¿Qué caracteriza a Kanban como metodología ágil?", o:["Organiza el trabajo en sprints con roles fijos","Visualiza el flujo de tareas en un tablero continuo","Elimina la necesidad de tareas","Solo se usa en proyectos grandes"], c:1},
    {p:"¿Por qué es útil el inglés técnico en programación?", o:["Porque es obligatorio por ley","Porque gran parte de la documentación y comunidad está en inglés","Porque los lenguajes de programación cambian de nombre","Porque no se puede programar sin él"], c:1},
    {p:"¿Qué es un reporte de avances?", o:["Un tipo de prueba automatizada","Comunicar qué se ha hecho, qué falta y qué obstáculos hay","Un documento legal","Un tipo de commit"], c:1},
    {p:"¿Qué se busca al dar code review de forma constructiva?", o:["Señalar errores para hacer sentir mal al otro","Ayudar a mejorar el resultado con retroalimentación útil","Rechazar todo el código posible","Evitar comentar nada"], c:1},
    {p:"¿Qué es el pensamiento crítico aplicado a lo técnico?", o:["Aceptar cualquier solución sin revisarla","Cuestionar suposiciones y evaluar evidencia antes de decidir","Copiar código de internet sin revisarlo","Evitar hacer preguntas"], c:1},
]},

{ id:18, titulo:"Preparación para conseguir empleo", temas:[
    {n:"Currículum técnico", d:"Un CV enfocado en mostrar proyectos, tecnologías y resultados concretos."},
    {n:"GitHub profesional", d:"Un perfil de GitHub organizado, con repositorios limpios y documentados."},
    {n:"Portafolio", d:"Una colección de tus mejores proyectos, presentados de forma clara."},
    {n:"LinkedIn", d:"La red profesional donde reclutadores buscan candidatos."},
    {n:"Entrevistas técnicas", d:"Te piden resolver problemas de programación, muchas veces explicando tu razonamiento."},
    {n:"Estructuras de datos para entrevistas", d:"Los temas de estructuras y algoritmos más preguntados en procesos de selección técnica."},
    {n:"SQL", d:"Consultas y manejo de bases de datos relacionales, tema recurrente en entrevistas de backend o datos."},
    {n:"Debugging", d:"Encontrar y corregir errores en vivo, una habilidad que muchas entrevistas evalúan directamente."},
    {n:"Diseño de sistemas", d:"En entrevistas senior, se pide diseñar la arquitectura de un sistema a gran escala."},
    {n:"Entrevistas conductuales", d:"Evalúan cómo trabajas con otros y tomas decisiones, más allá de lo técnico."},
    {n:"Explicación de proyectos", d:"Poder contar claramente qué hiciste, por qué, y qué aprendiste."},
    {n:"Búsqueda de empleos junior", d:"Saber dónde y cómo buscar las primeras oportunidades."},
    {n:"Prácticas profesionales", d:"Oportunidades de trabajar en un entorno real mientras sigues aprendiendo."},
    {n:"Open source", d:"Contribuir a proyectos de código abierto da experiencia real y visibilidad pública."},
    {n:"Freelance", d:"Trabajar de forma independiente para distintos clientes."},
    {n:"Cotizaciones", d:"Calcular cuánto cobrar por un proyecto freelance."},
    {n:"Contratos", d:"Acuerdos formales que protegen tanto al freelancer como al cliente."},
    {n:"Entregas por etapas", d:"Dividir un proyecto freelance en partes entregables, reduciendo el riesgo."},
    {n:"Protección contra estafas", d:"Precauciones para evitar clientes que no pagan o condiciones injustas."},
], preguntas:[
    {p:"¿Qué debería mostrar un currículum técnico, además de estudios?", o:["Solo certificados","Proyectos, tecnologías y resultados concretos","Solo el nombre de la escuela","Nada más que contacto"], c:1},
    {p:"¿Qué evalúan típicamente las entrevistas conductuales?", o:["Solo conocimientos de algoritmos","Cómo trabajas con otros y tomas decisiones, más allá de lo técnico","La velocidad de tu computadora","Tu ortografía"], c:1},
    {p:"¿Por qué contribuir a proyectos open source ayuda en la búsqueda de empleo?", o:["Porque es obligatorio","Porque da experiencia real y visibilidad pública de tu trabajo","Porque paga muy bien siempre","Porque reemplaza la entrevista técnica"], c:1},
    {p:"¿Para qué sirven las entregas por etapas en un proyecto freelance?", o:["Para cobrar todo de una vez","Para reducir el riesgo dividiendo el proyecto en partes entregables","Para tardar más tiempo","Para evitar hacer un contrato"], c:1},
    {p:"¿Qué protege un contrato en un trabajo freelance?", o:["Solo al cliente","A ambas partes, definiendo qué se entrega y en qué condiciones","Solo el pago","Nada, son solo formalidad"], c:1},
    {p:"¿Qué se evalúa normalmente en una entrevista técnica?", o:["Solo tu currículum","Resolver problemas de programación, muchas veces explicando tu razonamiento","Tu perfil de redes sociales","Tus calificaciones escolares"], c:1},
]},

];
